// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/public": {
            "get": {
                "description": "Get the public key used for signature verification",
                "produces": [
                    "text/plain"
                ],
                "summary": "Get the public key",
                "responses": {
                    "200": {
                        "description": "The key",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sign": {
            "post": {
                "description": "Get an RSA PSS signature for given text",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "summary": "Sign the given text",
                "parameters": [
                    {
                        "description": "Text to sign",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the signature",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Can't read body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "415": {
                        "description": "Content-Type is not text/plain",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Issues with cryptography algorithm",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/verify": {
            "post": {
                "description": "Verify that given signature matches given text, using the public key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Verify text + signature",
                "parameters": [
                    {
                        "description": "Data-signature pair to verify; signature can be passed as base-64 string",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/signer.VerifyBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/signer.VerifyOkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/signer.VerifyErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "signer.VerifyBody": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "signature": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "signer.VerifyErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "signer.VerifyOkResponse": {
            "type": "object",
            "properties": {
                "correct": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
