info:
  contact: {}
paths:
  /public:
    get:
      description: Get the public key used for signature verification in PEM format
      produces:
      - text/plain
      responses:
        "200":
          description: The key
          schema:
            type: string
      summary: Get the public key
  /sign:
    post:
      consumes:
      - text/plain
      description: Get an RSA PSS signature for given text
      parameters:
      - description: Text to sign
        in: body
        name: body
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Returns the dated text with a signature
          schema:
            type: string
        "400":
          description: Can't read body
          schema:
            type: string
        "415":
          description: Content-Type is not text/plain
          schema:
            type: string
        "500":
          description: Issues with cryptography algorithm
          schema:
            type: string
      summary: Sign the given text
  /verify:
    post:
      consumes:
      - text/plain
      description: Verify given signed text; quality of life feature, can be done
        locally with the public key.
      parameters:
      - description: 'Signed text to verify; '
        in: body
        name: body
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Signature matches
          schema:
            type: string
        "400":
          description: Can't read body
          schema:
            type: string
        "409":
          description: Signature doesn't match
          schema:
            type: string
        "415":
          description: Content-Type is not text/plain
          schema:
            type: string
      summary: Verify text + signature
swagger: "2.0"
