definitions:
  signer.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  signer.SignBody:
    properties:
      text:
        type: string
    type: object
  signer.SignaturePair:
    properties:
      dated_text:
        type: string
      signature:
        type: string
    type: object
  signer.VerifyOkResponse:
    type: object
info:
  contact: {}
paths:
  /public:
    get:
      description: Get the public key used for signature verification in PEM format
      produces:
      - text/plain
      responses:
        "200":
          description: The key
          schema:
            type: string
      summary: Get the public key
  /sign:
    post:
      consumes:
      - application/json
      description: Get an RSA PSS signature for given text
      parameters:
      - description: Text to sign
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/signer.SignBody'
      produces:
      - application/json
      responses:
        "200":
          description: Returns the signature
          schema:
            $ref: '#/definitions/signer.SignaturePair'
        "400":
          description: Can't bind JSON from body
          schema:
            $ref: '#/definitions/signer.ErrorResponse'
        "500":
          description: Issues with cryptography algorithm
          schema:
            $ref: '#/definitions/signer.ErrorResponse'
      summary: Sign the given text
  /verify:
    post:
      consumes:
      - application/json
      description: Verify that given signature matches given text; quality of life
        feature, can be done locally with the public key.
      parameters:
      - description: Data-signature pair to verify; signature can be passed as base-64
          string
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/signer.SignaturePair'
      produces:
      - application/json
      responses:
        "200":
          description: Signature matches
          schema:
            $ref: '#/definitions/signer.VerifyOkResponse'
        "400":
          description: Bad JSON
          schema:
            $ref: '#/definitions/signer.ErrorResponse'
        "409":
          description: Signature doesn't match
          schema:
            $ref: '#/definitions/signer.ErrorResponse'
      summary: Verify text + signature
swagger: "2.0"
