definitions:
  signer.VerifyBody:
    properties:
      data:
        type: string
      signature:
        items:
          type: integer
        type: array
    type: object
  signer.VerifyErrorResponse:
    properties:
      error:
        type: string
    type: object
  signer.VerifyOkResponse:
    properties:
      correct:
        type: boolean
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /public:
    get:
      description: Get the public key used for signature verification
      produces:
      - text/plain
      responses:
        "200":
          description: The key
          schema:
            type: string
      summary: Get the public key
  /sign:
    post:
      consumes:
      - text/plain
      description: Get an RSA PSS signature for given text
      parameters:
      - description: Text to sign
        in: body
        name: body
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Returns the signature
          schema:
            type: string
        "400":
          description: Can't read body
          schema:
            type: string
        "415":
          description: Content-Type is not text/plain
          schema:
            type: string
        "500":
          description: Issues with cryptography algorithm
          schema:
            type: string
      summary: Sign the given text
  /verify:
    post:
      consumes:
      - application/json
      description: Verify that given signature matches given text, using the public
        key
      parameters:
      - description: Data-signature pair to verify; signature can be passed as base-64
          string
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/signer.VerifyBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/signer.VerifyOkResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/signer.VerifyErrorResponse'
      summary: Verify text + signature
swagger: "2.0"
