name: Run tests & check docker compose
on: [push]
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Run tests
      working-directory: ./signer/src
      run: go test .

  docker:
    name: Check docker compose
    runs-on: ubuntu-22.04
    needs: tests
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up docker compose
      uses: docker/setup-buildx-action@v2
    - name: Run docker compose
      run: |
        openssl genpkey -algorithm RSA -out signer/private.pem -pkeyopt rsa_keygen_bits:2048
        mv .env.example .env
        docker compose up -d --build --wait
        curl localhost:8080/public
        docker compose down

